aa_fitness_distributions: /Users/afarineshpanahy/Desktop/slim-tree/slim-tree/tests/testFiles/table_fitness_dists_full.csv
backup: false
burn_in: 100
calculate_selection: false
coding_ratio: 1.0
codon_stationary_distributions: /Users/afarineshpanahy/Desktop/slim-tree/slim-tree/tests/testFiles/table_stationary_dists_full.csv
count_subs: false
fasta_file: null
gene_count: 1
genome_length: 10
high_performance_computing: false
input_tree: ex7_tree.txt
jukes_cantor: true
mutation_matrix: null
mutation_rate: 2.5e-06
neutral_evolution: false
nonWF: true
output_gens: false
partition: null
polymorphisms: false
population_size: 50
recombination_rate: 2.5e-08
sample_size: all
split_ratio: 0.5
substitutions: false
theta: 0.0005
time: null
tree_data_file: null
